PREFIX kg: <https://example.org/clinical-kg/>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
PREFIX prov: <http://www.w3.org/ns/prov#>
PREFIX obo: <http://purl.obolibrary.org/obo/>
SELECT ?subject ?predicate ?object WHERE {
 GRAPH <https://example.org/clinical-kg/graph/inferred> { ?subject ?predicate ?object }
 FILTER((?subject = obo:MONDO_0005148 && ((?predicate = rdfs:subClassOf && ?object != obo:MONDO_0005148 && STRSTARTS(STR(?object), STR(obo:))) || ?object = kg:PhenotypeAnnotatedConcept)) || ?predicate = kg:phenotypeOf)
} ORDER BY ?subject ?predicate ?object
